// This file is generated by icon spritesheet generator

export const iconNames = [
	"user",
	"trash",
	"shield-alert",
	"settings",
	"search",
	"pencil",
	"panel-left-open",
	"panel-left-close",
	"menu",
	"log-out",
	"layout-dashboard",
	"key-round",
	"fingerprint",
	"ellipsis-vertical",
	"chevron-up",
	"chevron-right",
	"chevron-left",
	"chevron-down",
] as const;

export type IconName = (typeof iconNames)[number];
